# Generated by Django 4.2 on 2023-05-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(db_index=True, default=False, max_length=455),
        ),
    ]
