# Generated by Django 4.2 on 2023-05-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_email_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(db_index=True, default=False, unique=True),
        ),
    ]
