# Generated by Django 4.2 on 2023-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=models.IntegerField(db_index=True, default=False, unique=True), max_length=255),
        ),
    ]
