# Generated by Django 4.2 on 2023-05-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
