# Generated by Django 4.2 on 2023-05-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='uuid',
        ),
        migrations.AddField(
            model_name='group',
            name='group_id',
            field=models.IntegerField(default=False, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='owner_id',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]
