# Generated by Django 4.2 on 2023-05-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_remove_group_uuid_group_group_id_group_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='players_choices',
            field=models.IntegerField(default=False),
        ),
    ]
